# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php
###
  
trigger:
- azure-pipelines

pool:
  name: bala-ec2-agent-pool

variables:
  phpVersion: 8.1

steps:  
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      **/*
      !.git/**/*
    TargetFolder: '/var/nava360/dashboard/latest_$(Build.BuildNumber)'
- script: |
    cd /var/nava360/dashboard/latest_'$(Build.BuildNumber)'
    pwd
    composer install --no-interaction --prefer-dist
  displayName: 'composer install'
    
