
# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php
###
  
trigger:
- azure-pipelines

pool:
  name: bala-ec2-agent-pool

variables:
  phpVersion: 8.1

steps:  
- task: CopyFiles@2
  displayName: 'Move latest code'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      **/*
      !.git/**/*
    TargetFolder: '/var/nava360/dashboard/latest_$(Build.BuildNumber)'
- task: Bash@3
  displayName: 'composer install'
  inputs:
   targetType: 'inline'
   script: |
     #composer install --no-interaction --prefer-dist
     composer install
   failOnStderr: true
   workingDirectory: "/var/nava360/dashboard/latest_$(Build.BuildNumber)"
# - script: |
#     cd /var/nava360/dashboard/latest_'$(Build.BuildNumber)'
#     echo 'Current wokring directory: '; pwd
#     #composer install --no-interaction --prefer-dist
#     composer install
#   displayName: 'composer install'
- script: |
    cd /var/nava360/dashboard/latest_'$(Build.BuildNumber)'
    echo 'Current wokring directory: '; pwd
    #php artisan migrate
    #php artisan migrate --path=database/migrations/landlord --database=landlord --force
    #php artisan tenants:artisan "migrate --path=database/migrations/tenant --database=tenant --force"
  displayName: 'Artisan Migrate'
- script: |
    cd /var/nava360/dashboard/latest_'$(Build.BuildNumber)/nodejs'
    echo 'Current wokring directory: '; pwd
    npm link ioredis socket.io node-env-file
  displayName: 'Link Node Packages'
- script: |
    cd /var/nava360/dashboard/latest_'$(Build.BuildNumber)'
    echo 'Current wokring directory: '; pwd
    # php artisan config:cache
    # php artisan translations:cache
  displayName: 'Config cache'
- script: |
    cd /var/nava360/dashboard/latest_'$(Build.BuildNumber)'
    echo 'Current wokring directory: '; pwd
    # php artisan route:cache
    # php artisan view:cache
  displayName: 'Route & View Cache'
- script: |
    cd /var/nava360/dashboard/
    echo 'Current wokring directory: '; pwd
    ln -sf latest_'$(Build.BuildNumber)' current
  displayName: 'Activate New Release'
- script: |
    cd /var/nava360/dashboard/latest_'$(Build.BuildNumber)'
    echo 'Current wokring directory: '; pwd
    # sudo php artisan horizon:terminate
  displayName: 'Restart Queue'
- script: |
    cd /var/nava360/dashboard/latest_'$(Build.BuildNumber)'
    echo 'Current wokring directory: '; pwd
    #php artisan deploy:show-banner
  displayName: 'Show Refresh banner'




