# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php
###
  
trigger:
- azure-pipelines

pool:
  name: bala-ec2-agent-pool

variables:
  phpVersion: 8.1

steps:
- script: |
    timestamp=$(date +%Y%m%d_%H%M%S)
    release='$(Agent.HomeDirectory)_$(timestamp)'
    echo '$release'
  displayName: 'release floder name'
  
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      **/*
      !.git/**/*
    TargetFolder: '/var/nava360/dashboard/latest_$(date +%Y%m%d_%H%M%S)'
    
